/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaces;

import persistencia.BD;
import controlador.ControladorCadastroAluno;
import controlador.ControladorCadastroInstrutor;
import controlador.ControladorCadastroFichaTreino;

public class JanelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        BD.criaConexão();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        barra_menuMenuBar = new javax.swing.JMenuBar();
        gerenciarMenu = new javax.swing.JMenu();
        gerenciar_alunosMenuItem = new javax.swing.JMenuItem();
        gerenciar_instrutoresMenuItem = new javax.swing.JMenuItem();
        fichas_treinoMenuItem = new javax.swing.JMenuItem();
        PesquisarMenu = new javax.swing.JMenu();
        pesquisarMenuItem = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Academia SportLife");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        gerenciarMenu.setText("Gerenciar");

        gerenciar_alunosMenuItem.setText("Alunos");
        gerenciar_alunosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenciar_alunosMenuItemActionPerformed(evt);
            }
        });
        gerenciarMenu.add(gerenciar_alunosMenuItem);

        gerenciar_instrutoresMenuItem.setText("Instrutores");
        gerenciar_instrutoresMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenciar_instrutoresMenuItemActionPerformed(evt);
            }
        });
        gerenciarMenu.add(gerenciar_instrutoresMenuItem);

        fichas_treinoMenuItem.setText("Fichas de Treino");
        fichas_treinoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fichas_treinoMenuItemActionPerformed(evt);
            }
        });
        gerenciarMenu.add(fichas_treinoMenuItem);

        barra_menuMenuBar.add(gerenciarMenu);

        PesquisarMenu.setText("Pesquisar");

        pesquisarMenuItem.setText("Abrir janela");
        pesquisarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarMenuItemActionPerformed(evt);
            }
        });
        PesquisarMenu.add(pesquisarMenuItem);

        barra_menuMenuBar.add(PesquisarMenu);

        setJMenuBar(barra_menuMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gerenciar_alunosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciar_alunosMenuItemActionPerformed
        new ControladorCadastroAluno();
    }//GEN-LAST:event_gerenciar_alunosMenuItemActionPerformed

    private void gerenciar_instrutoresMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciar_instrutoresMenuItemActionPerformed
           new ControladorCadastroInstrutor();
    }//GEN-LAST:event_gerenciar_instrutoresMenuItemActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        BD.fechaConexão();
    }//GEN-LAST:event_formWindowClosed

    private void fichas_treinoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fichas_treinoMenuItemActionPerformed
        new ControladorCadastroFichaTreino();
    }//GEN-LAST:event_fichas_treinoMenuItemActionPerformed

    private void pesquisarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarMenuItemActionPerformed
        new JanelaPesquisa().setVisible(true);
        
    }//GEN-LAST:event_pesquisarMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu PesquisarMenu;
    private javax.swing.JMenuBar barra_menuMenuBar;
    private javax.swing.JMenuItem fichas_treinoMenuItem;
    private javax.swing.JMenu gerenciarMenu;
    private javax.swing.JMenuItem gerenciar_alunosMenuItem;
    private javax.swing.JMenuItem gerenciar_instrutoresMenuItem;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem pesquisarMenuItem;
    // End of variables declaration//GEN-END:variables
}
