
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaces;

import entidade.FormularioConsulta;
import entidade.FormularioConsulta.Entidade;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author jeovano
 */
public class JanelaPesquisa extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPesquisa
     */
    public JanelaPesquisa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PesquisabuttonGroup = new javax.swing.ButtonGroup();
        botõesPanel = new javax.swing.JPanel();
        ConsultarButton = new javax.swing.JButton();
        LimparButton = new javax.swing.JButton();
        CancelarButton = new javax.swing.JButton();
        BairroTextField = new javax.swing.JTextField();
        nomeTextField = new javax.swing.JTextField();
        horarioTextField = new javax.swing.JTextField();
        bairroLabel = new javax.swing.JLabel();
        horarioLabel = new javax.swing.JLabel();
        NomeLabel = new javax.swing.JLabel();
        RadioButtonPanel = new javax.swing.JPanel();
        InstrutorRadioButton = new javax.swing.JRadioButton();
        AlunoRadioButton = new javax.swing.JRadioButton();
        FichaRadioButton = new javax.swing.JRadioButton();
        TextAreaPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultadosTextArea = new javax.swing.JTextArea();
        Pesquisa_resultLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        DataNascTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        logradouroTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisar");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        botõesPanel.setBorder(null);

        ConsultarButton.setText("Consultar");
        ConsultarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarButtonActionPerformed(evt);
            }
        });

        LimparButton.setText("Limpar");
        LimparButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparButtonActionPerformed(evt);
            }
        });

        CancelarButton.setText("Cancelar");
        CancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout botõesPanelLayout = new javax.swing.GroupLayout(botõesPanel);
        botõesPanel.setLayout(botõesPanelLayout);
        botõesPanelLayout.setHorizontalGroup(
            botõesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botõesPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(ConsultarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LimparButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CancelarButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        botõesPanelLayout.setVerticalGroup(
            botõesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botõesPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(botõesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConsultarButton)
                    .addComponent(LimparButton)
                    .addComponent(CancelarButton))
                .addGap(24, 24, 24))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 18, 18);
        getContentPane().add(botõesPanel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        getContentPane().add(BairroTextField, gridBagConstraints);

        nomeTextField.setDisabledTextColor(new java.awt.Color(132, 130, 127));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        getContentPane().add(nomeTextField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        getContentPane().add(horarioTextField, gridBagConstraints);

        bairroLabel.setText("Bairro");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        getContentPane().add(bairroLabel, gridBagConstraints);

        horarioLabel.setText("Horário");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        getContentPane().add(horarioLabel, gridBagConstraints);

        NomeLabel.setText("Nome");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        getContentPane().add(NomeLabel, gridBagConstraints);

        RadioButtonPanel.setBorder(null);

        PesquisabuttonGroup.add(InstrutorRadioButton);
        InstrutorRadioButton.setText("Instrutor");
        InstrutorRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                InstrutorRadioButtonItemStateChanged(evt);
            }
        });

        PesquisabuttonGroup.add(AlunoRadioButton);
        AlunoRadioButton.setText("Aluno");
        AlunoRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                AlunoRadioButtonItemStateChanged(evt);
            }
        });
        AlunoRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlunoRadioButtonActionPerformed(evt);
            }
        });

        PesquisabuttonGroup.add(FichaRadioButton);
        FichaRadioButton.setText("Ficha de Treino");
        FichaRadioButton.setToolTipText("");
        FichaRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                FichaRadioButtonItemStateChanged(evt);
            }
        });
        FichaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FichaRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RadioButtonPanelLayout = new javax.swing.GroupLayout(RadioButtonPanel);
        RadioButtonPanel.setLayout(RadioButtonPanelLayout);
        RadioButtonPanelLayout.setHorizontalGroup(
            RadioButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RadioButtonPanelLayout.createSequentialGroup()
                .addComponent(InstrutorRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FichaRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AlunoRadioButton)
                .addContainerGap())
        );
        RadioButtonPanelLayout.setVerticalGroup(
            RadioButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RadioButtonPanelLayout.createSequentialGroup()
                .addGroup(RadioButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InstrutorRadioButton)
                    .addComponent(FichaRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AlunoRadioButton))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        getContentPane().add(RadioButtonPanel, gridBagConstraints);

        TextAreaPanel.setBorder(null);

        resultadosTextArea.setEditable(false);
        resultadosTextArea.setBackground(new java.awt.Color(192, 189, 187));
        resultadosTextArea.setColumns(20);
        resultadosTextArea.setRows(5);
        resultadosTextArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(resultadosTextArea);

        Pesquisa_resultLabel.setText("Resultados: ");

        javax.swing.GroupLayout TextAreaPanelLayout = new javax.swing.GroupLayout(TextAreaPanel);
        TextAreaPanel.setLayout(TextAreaPanelLayout);
        TextAreaPanelLayout.setHorizontalGroup(
            TextAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TextAreaPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(TextAreaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pesquisa_resultLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TextAreaPanelLayout.setVerticalGroup(
            TextAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TextAreaPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Pesquisa_resultLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        getContentPane().add(TextAreaPanel, gridBagConstraints);

        jLabel1.setText("Data Nascimento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        getContentPane().add(jLabel1, gridBagConstraints);

        DataNascTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataNascTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        getContentPane().add(DataNascTextField, gridBagConstraints);

        jLabel2.setText("Logradouro");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        getContentPane().add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        getContentPane().add(logradouroTextField, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConsultarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarButtonActionPerformed
        if(PesquisabuttonGroup.getSelection() == null) {
            JOptionPane.showMessageDialog(this,"NENHUM GRUPO SELECIONADO","ERRO", JOptionPane.WARNING_MESSAGE);
        }
        else {
            FormularioConsulta novo = obterFormulario();
            resultadosTextArea.setText(FormularioConsulta.Pesquisar(novo));
        }
    }//GEN-LAST:event_ConsultarButtonActionPerformed

    private void CancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelarButtonActionPerformed

    private void LimparButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparButtonActionPerformed
        limparCampos();
    }//GEN-LAST:event_LimparButtonActionPerformed

    private void DataNascTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataNascTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DataNascTextFieldActionPerformed

    private void AlunoRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlunoRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlunoRadioButtonActionPerformed

    private void AlunoRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_AlunoRadioButtonItemStateChanged
        horarioTextField.setEditable(false);
        horarioTextField.setBackground(Color.GRAY);
    }//GEN-LAST:event_AlunoRadioButtonItemStateChanged

    private void InstrutorRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_InstrutorRadioButtonItemStateChanged
        horarioTextField.setEditable(false);
        horarioTextField.setBackground(Color.GRAY); 
    }//GEN-LAST:event_InstrutorRadioButtonItemStateChanged

    private void FichaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FichaRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FichaRadioButtonActionPerformed

    private void FichaRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_FichaRadioButtonItemStateChanged
        horarioTextField.setEditable(true);
        horarioTextField.setBackground(Color.white);
    }//GEN-LAST:event_FichaRadioButtonItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPesquisa().setVisible(true);
            }
        });
    }
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AlunoRadioButton;
    private javax.swing.JTextField BairroTextField;
    private javax.swing.JButton CancelarButton;
    private javax.swing.JButton ConsultarButton;
    private javax.swing.JTextField DataNascTextField;
    private javax.swing.JRadioButton FichaRadioButton;
    private javax.swing.JRadioButton InstrutorRadioButton;
    private javax.swing.JButton LimparButton;
    private javax.swing.JLabel NomeLabel;
    private javax.swing.JLabel Pesquisa_resultLabel;
    private javax.swing.ButtonGroup PesquisabuttonGroup;
    private javax.swing.JPanel RadioButtonPanel;
    private javax.swing.JPanel TextAreaPanel;
    private javax.swing.JLabel bairroLabel;
    private javax.swing.JPanel botõesPanel;
    private javax.swing.JLabel horarioLabel;
    private javax.swing.JTextField horarioTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField logradouroTextField;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JTextArea resultadosTextArea;
    // End of variables declaration//GEN-END:variables

    public void limparCampos() {
        PesquisabuttonGroup.clearSelection();
        BairroTextField.setText("");
        nomeTextField.setText("");
        horarioTextField.setText("");
        logradouroTextField.setText("");
        DataNascTextField.setText("");
        resultadosTextArea.setText("");
        
    }
    
    public FormularioConsulta obterFormulario() {
        String nome, horario, logradouro, bairro, data;
        Entidade selecionado;
        
        nome = (nomeTextField.getText().equals("")) ? null : nomeTextField.getText();
        horario = (horarioTextField.getText().equals("")) ? null : horarioTextField.getText();
        data = (DataNascTextField.getText().equals("")) ? null : DataNascTextField.getText();
        logradouro = (logradouroTextField.getText().equals("")) ? null : logradouroTextField.getText();
        bairro = (BairroTextField.getText().equals("")) ? null : BairroTextField.getText();
        
        if (AlunoRadioButton.isSelected()) {
            selecionado = Entidade.ALUNO;
        }
        else {
            if (InstrutorRadioButton.isSelected()) {
                selecionado = Entidade.INSTRUTOR;
            }
            else {
                selecionado = Entidade.FICHA;
            }
        }
        
        return new FormularioConsulta(nome, horario, logradouro, bairro, data, selecionado);
    }


}
